name: chasis
description: Chasis orquestador de microfrontends en Flutter.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.2.0  # Manejo de navegación desacoplada
  dio: ^5.4.0         # Cliente HTTP avanzado para llamadas a microfrontends
  provider: ^6.0.5    # Manejo de estado global para autenticación
  json_annotation: ^4.8.1 # Para manejar respuestas JSON

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4  # Para generar código (si se usa con json_serializable)
  json_serializable: ^6.7.1 # Para manejar JSON de forma automática

flutter:
  uses-material-design: true
